### ISSUE TITLE
error on start ^-^

### ISSUE THREAD

**Issue by mvolz** [jpvincent/webperf-training#1]
```
 npm start

> webperf-training@1.0.0 start
> nodemon serve-static.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): serve-static.js
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node serve-static.js`
_tls_common.js:129
      c.context.setCert(cert);
                ^

Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.setSecureContext (_tls_wrap.js:1323:27)
    at Server (_tls_wrap.js:1181:8)
    at Server (https.js:66:14)
    at Server._init (/home/marielle/code/webperf-training/node_modules/spdy/lib/spdy/server.js:62:10)
    at new Server (/home/marielle/code/webperf-training/node_modules/spdy/lib/spdy/server.js:25:10)
    at Function.create (/home/marielle/code/webperf-training/node_modules/spdy/lib/spdy/server.js:30:12)
    at Object.create [as createServer] (/home/marielle/code/webperf-training/node_modules/spdy/lib/spdy/server.js:286:27)
    at Object.<anonymous> (/home/marielle/code/webperf-training/serve-static.js:56:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  library: 'SSL routines',
  function: 'SSL_CTX_use_certificate',
  reason: 'ee key too small',
  code: 'ERR_SSL_EE_KEY_TOO_SMALL'
}
[nodemon] app crashed - waiting for file changes before starting...
```

Using node v14.16.1 (npm v7.10.0)

**Comment by jpvincent** [comment]
Thank you for the report !
I knew there was problems when installing, but not at start. Thank you for the versions, I'll see if I can reproduce this.
